# Generated by Django 4.1.5 on 2023-10-19 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ryph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 19, 11, 42, 43, 37780))),
                ('title', models.CharField(max_length=200)),
                ('cate', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploded_files')),
                ('comments', models.TextField()),
            ],
        ),
    ]
